on:
  push:
    branches: [ main ]
jobs:
  build:
    name: Build & package deployment
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
    - name: Build CLI
      run: mvn -Pcli package
    - uses: actions/upload-artifact@v2
      with:
         name: CLI
         path: target/ebookipedia.jar
    - name: Build API & deploy it as a Github Maven package
      run: mvn -Papi -Dgithub.user=hiebra -Dgithub.token=${{secrets.GITHUB_TOKEN}} deploy
  deploy:
    name: Main (CLI) deployment
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checking out ebookipedia/exe
      uses: actions/checkout@v2
      with:
          repository: ebookipedia/exe
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - name: Downloading build.jar into ./docs
      uses: actions/download-artifact@v2
      with:
        name: CLI
        path: docs
    - name: Display structure of downloaded files
      run: |
        ls -R
        jar tf ./docs/ebookipedia.jar
    - name: Commit & Push changes
      uses: actions-js/push@master
      with:
        repository: ebookipedia/exe
        github_token: ${{ secrets.DEPLOYMENT }}
